# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d09fe06077435541bffed7be80f8914ee9188458e9a8b57a25c5c8a7161648c14897030f250624e6a0296dbd18fc5223b15ed4d8d7a55f823e63f1153f89967d

test:
  secret_key_base: 9562d85ed230640183bf6e6000b5f279e884ff7251ad8dfe964076ba42fc5fce19134dd2c77d1141c75749527bb1f4416949dc3b067b402981d26383b33e3514

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
